### ISSUE TITLE
Double tabs in server response format when skipping parts of the processing

### ISSUE THREAD

**Issue by jsteggink** [proycon/frog#1]
Hello,

When skipping parts of the processing, FrogAPI inserts double tabs. This makes it more difficult to parse the results. Would it be possible to return a single tab per column? This way you can just split a line on tabs and don't have to do complicated counting. I'm not sure if any of the other Frog clients take this into account. Might be worth to asks the developers of the clients what their opinion is.

Regards,
Jeroen

**Comment by proycon** [comment]
Hi Jeroen,

True, for backward-compatibility with older clients, Frog ensures that the same type of data is always in the same column. The best solution for now is to simply collapse multiple tabs into one client-side if this is not a desired behaviour. For more advanced parsing, it is recommended to use the FoLiA XML output instead.

Regards,
